=== LiveSatomi/three-houses-recruitment/src/data/schemas/characterSchema.json
{
    "title": "Character",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "required": [
        "_id",
        "name",
        "portraitUrl",
        "gifts",
        "lostItems",
        "meals",
        "routes"
    ],
    "description": "Fire Emblem Character Schema",
    "additionalProperties": false,
    "definitions": {
        "characterId": {
            "description": "Character id",
            "type": "string",
            "enum": ["ashe", "felix", "lysithea", "raphael"]
        }
    },
    "properties": {
        "_id": {
            "$ref": "#/definitions/characterId"
        },
        "name": {
            "description": "Character Name",
            "type": "string"
        },
        "portraitUrl": {
            "description": "URL for the character portrait, relative to src",
            "type": "string",
            "format": "uri-template"
        },
        "gifts": {
            "description": "List of liked gifts",
            "type": "array",
            "items": {
                "$ref": "giftSchema.json#/definitions/giftId"
            }
        },
        "lostItems": {
            "description": "List of liked gifts",
            "type": "array",
            "items": {
                "$ref": "lostItemSchema.json#/definitions/lostItemId"
            }
        },
        "meals": {
            "description": "Lists of liked and disliked meals",
            "type": "object",
            "required": ["liked", "disliked"],
            "additionalProperties": false,
            "properties": {
                "liked": {
                    "type": "array",
                    "items": {
                        "$ref": "mealSchema.json#/definitions/mealId"
                    }
                },
                "disliked": {
                    "type": "array",
                    "items": {
                        "$ref": "mealSchema.json#/definitions/mealId"
                    }
                }
            }
        },
        "routes": {
            "description": "Route specific information for the character",
            "type": "array",
            "items": {
                "type": "object",
                "required": ["id", "chapters"],
                "additionalProperties": false,
                "properties": {
                    "id": {
                        "$ref": "monasterySchema.json#/definitions/routeId"
                    },
                    "chapters": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "required": ["available"],
                            "additionalProperties": false,
                            "properties": {
                                "available": {
                                    "type": "boolean"
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

=== LiveSatomi/three-houses-recruitment/src/data/characters/lysithea.json
{
    "_id": "lysithea",
    "name": "Lysithea",
    "portraitUrl": "characters/portrait/lysithea.png",
    "gifts": [
        "tasty-baked-treat",
        "lily",
        "armored-bear-stuffy",
        "arithmetic-textbook",
        "book-of-crest-designs"
    ],
    "lostItems": ["encyclopediaOfSweets", "princessDoll", "newBottleOfPerfume"],
    "meals": {
        "liked": ["peachSorbet"],
        "disliked": ["friedCrayfish"]
    },
    "routes": [
        {
            "id": "white-clouds",
            "chapters": [
                {
                    "available": true
                },
                {
                    "available": true
                },
                {
                    "available": true
                },
                {
                    "available": true
                },
                {
                    "available": true
                },
                {
                    "available": true
                },
                {
                    "available": true
                },
                {
                    "available": true
                },
                {
                    "available": true
                },
                {
                    "available": true
                }
            ]
        }
    ]
}
